### ISSUE TITLE
Letting Mtn Ops move instrument FW -- Populate/Populate done button from old gui

### ISSUE THREAD

**Issue by dsand** [so-90prime/bok-90prime-gui#4]
There is a special command on fwgui that mountain ops uses at the end of the run or when they want to change filters.  it is the 'populate' button on the old gui.
if you press 'populate' it lets you move the filter wheel manually by pressing a button on the instrument (see picture).  they need to be able to do this to change filters.
'populate done' then takes away control of the filter wheel from the button on the
![IMG_2440](https://user-images.githubusercontent.com/9013064/205338865-4b137efa-efc1-4a00-9830-757ec96fdaa0.jpg)
 instrument, so you need to do that after you've changed filters.

This issue is to implement something similar on the new gui.

**Comment by pndaly** [comment]
This is great as neither Dan nor I could ever figure out what 'Populate' and 'PopDone' was used for! The good news is that these commands are already in the new GUI. In the astronomer version, it's hidden but in the engineering GUI is visible. The engineering GUI can either be accessed via xephem or going to the astronomer GUI and adding '/indi' to the URL (so if you're running on bonsai, http://10.30.1.7:5905/indi).

**Comment by pndaly** [comment]
Also been documented in bokGalil.pdf, the handover document. Issue closed.
