### ISSUE TITLE
Pressing 'load filter' while filter wheel rotating causes big problems

### ISSUE THREAD

**Issue by dsand** [so-90prime/bok-90prime-gui#5]
@dsand did this tonight, just cause he was tired.  There should be a way to disable the 'load filter' button when the wheel is rotating.

**Comment by pndaly** [comment]
Load/Unload filter buttons removed from the astronomer GUI (but still available in the engineering GUI) as selecting a filter now does the unload / rotate / load for you. Any filter selection must be allowed to complete ... if you pick the wrong filter, let it finish before selecting the right one. Issue closed but we'll monitor it.
